# Generated by Django 4.2 on 2023-07-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduccion',
            field=models.CharField(default='Antes de la migracion', max_length=100),
            preserve_default=False,
        ),
    ]
